# Generated by Django 2.2.5 on 2019-09-15 18:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import grievance.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('token', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('campus', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GrievanceForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cg', models.CharField(max_length=10)),
                ('offShoot', models.CharField(max_length=10)),
                ('allocatedStation', models.CharField(max_length=500)),
                ('preferenceNumberOfAllocatedStation', models.IntegerField()),
                ('natureOfQuery', models.IntegerField()),
                ('applicationDate', models.DateTimeField()),
                ('preferedStation1', models.CharField(max_length=500)),
                ('preferedStation2', models.CharField(blank=True, max_length=500)),
                ('preferedStation3', models.CharField(blank=True, max_length=500)),
                ('preferedStation4', models.CharField(blank=True, max_length=500)),
                ('preferedStation5', models.CharField(blank=True, max_length=500)),
                ('document1', models.FileField(blank=True, upload_to=grievance.models.path_and_rename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), grievance.models.validate_document])),
                ('document2', models.FileField(blank=True, upload_to=grievance.models.path_and_rename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), grievance.models.validate_document])),
                ('document3', models.FileField(blank=True, upload_to=grievance.models.path_and_rename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), grievance.models.validate_document])),
                ('document4', models.FileField(blank=True, upload_to=grievance.models.path_and_rename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), grievance.models.validate_document])),
                ('document5', models.FileField(blank=True, upload_to=grievance.models.path_and_rename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), grievance.models.validate_document])),
                ('priority', models.IntegerField(blank=True)),
                ('student_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='grievance.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.IntegerField()),
                ('level', models.IntegerField()),
                ('status', models.IntegerField()),
                ('lastChangedDate', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=500)),
                ('level1Comment', models.CharField(blank=True, max_length=500)),
                ('level2Comment', models.CharField(blank=True, max_length=500)),
                ('newStation', models.CharField(blank=True, max_length=500)),
                ('campus', models.IntegerField(default=0)),
                ('natureOfQuery', models.IntegerField(default=0)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grievance.UserProfile')),
            ],
            options={
                'unique_together': {('student_id', 'attempt')},
            },
        ),
    ]
